# Generated by Django 5.2.4 on 2025-07-31 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('linkPrecedence', models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('deletedAt', models.DateTimeField(null=True)),
                ('linkedId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_by', to='IdentityManager.identities')),
            ],
            options={
                'db_table': 'bite_speed_indentities',
            },
        ),
    ]
