# Generated by Django 5.2.4 on 2025-07-31 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("IdentityManager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identities",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="identities",
            name="linkedId",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="IdentityManager.identities",
            ),
        ),
        migrations.AlterField(
            model_name="identities",
            name="phoneNumber",
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
    ]
